import React from "react";
import { Client } from "~/client/trpc/client";
import "~/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
